---
- name: Install required packages
  apt:
    name: wget
    state: present

- name: Download Zabbix repository package
  get_url:
    url: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/release/debian/pool/main/z/zabbix-release/zabbix-release_latest_{{ zabbix_version }}+debian12_all.deb"
    dest: /tmp/zabbix-release.deb

- name: Install Zabbix repository
  apt:
    deb: /tmp/zabbix-release.deb

- name: Update package cache
  apt:
    update_cache: yes

- name: Install Zabbix agent
  apt:
    name: zabbix-agent2
    state: present

- name: Configure Zabbix agent
  template:
    src: ../templates/zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    backup: yes
  register: zabbix_agent_config

- name: Restart Zabbix agent after config change
  systemd:
    name: zabbix-agent2
    state: restarted
  when: zabbix_agent_config.changed

- name: Create runtime directories
  file:
    path: "{{ item }}"
    state: directory
    owner: zabbix
    group: zabbix
    mode: '0755'
  loop:
    - /run/zabbix
    - /var/log/zabbix

- name: Start and enable agent
  systemd:
    name: zabbix-agent2
    state: started
    enabled: yes


